[MacOS] Move relauchOnMac out of WebUI.
When building tests the following error happens:

17:40:57  gen/chrome/test/data/webui/settings/preprocessed/test_lifetime_browser_proxy.ts:11:14 - error TS2420: Class 'TestLifetimeBrowserProxy' incorrectly implements interface 'LifetimeBrowserProxy'.
17:40:57    Property 'relaunchOnMac' is missing in type 'TestLifetimeBrowserProxy' but required in type 'LifetimeBrowserProxy'.
17:40:57
17:40:57  11 export class TestLifetimeBrowserProxy extends TestBrowserProxy implements
17:40:57                  ~~~~~~~~~~~~~~~~~~~~~~~~
17:40:57
17:40:57    gen/chrome/browser/resources/settings/tsc/lifetime_browser_proxy.d.ts:4:5
17:40:57      4     relaunchOnMac(): void;
17:40:57            ~~~~~~~~~~~~~~~~~~~~~~
17:40:57      'relaunchOnMac' is declared here.

which means we'd have to add a patch to test_lifetime_proxy.ts to add our relaunchOnMac functionality.

Instead, this change removes all relaunchOnMac functionality from WebUI and moves it
into the BrowserLifetimeHandler.